import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Navigation from "../components/Navigation";
import { ErrorBoundary } from "../components/ErrorBoundary";
import { VersionDisplay } from "../components/VersionDisplay";
import { VersionLogger } from "../components/VersionLogger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ErrorBoundary>
            <VersionLogger />
            <div className="flex min-h-screen w-full bg-gray-950">
              <Navigation />
              <main className="flex-1 px-2 pt-14 sm:pt-0 w-full sm:ml-20">
                {children}
              </main>
              <VersionDisplay />
            </div>
          </ErrorBoundary>
        </AuthProvider>
      </body>
    </html>
  );
}
